name = "codelume-remix-ai-studio-fe"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.production]
name = "codelume-remix-ai-studio-fe-prod"
route = ""
zone_id = ""

[build]
command = "pnpm build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]

[build.upload]
format = "service-worker"
